const authTypes = {
  LOGIN_USER_LOADING: 'LOGIN_USER_LOADING',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  HYDRATE_AUTH: 'HYDRATE_AUTH',
  RESET_PASSWORD_LOADING: 'RESET_PASSWORD_LOADING',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  CONFIRM_RESET_PASSWORD_LOADING: 'CONFIRM_RESET_PASSWORD_LOADING',
  CONFIRM_RESET_PASSWORD_SUCCESS: 'CONFIRM_RESET_PASSWORD_SUCCESS',
} as const;

export type AuthActionType = (typeof authTypes)[keyof typeof authTypes];

export default authTypes;
